SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE TABLE public.countries (
    id integer NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    iso3 character(3) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    iso2 character(2) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    phonecode character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    capital character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    currency character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    currency_symbol character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    tld character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    native character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    region character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    subregion character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    translations text COLLATE pg_catalog."default",
    latitude numeric(10,8) DEFAULT NULL::numeric,
    longitude numeric(11,8) DEFAULT NULL::numeric,
    emoji character varying(191) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    emojiu character varying(191) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    created_at timestamp without time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    flag smallint NOT NULL DEFAULT '1'::smallint,
    wikidataid character varying(255) COLLATE pg_catalog."default" DEFAULT 'Rapid API GeoDB Cities'::character varying,
    timezones jsonb,
    hashed character(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT countries_pkey PRIMARY KEY (id)
);


CREATE TABLE public.test_tbl1 (
    id integer NOT NULL,
    first_name character varying(128) NOT NULL,
    dts timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_name character varying(256) NOT NULL
);


ALTER TABLE public.test_tbl1 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.test_tbl1_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.test_tbl1
    ADD CONSTRAINT pk_test_tbl1 PRIMARY KEY (id);
